/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const BottomSide = IDL.Variant({
  'Top' : IDL.Null,
  'Back' : IDL.Null,
  'Left' : IDL.Null,
  'Right' : IDL.Null,
  'Front' : IDL.Null,
  'Bottom' : IDL.Null,
});
export const PartId = IDL.Nat;
export const Part = IDL.Record({
  'id' : PartId,
  'lengthCm' : IDL.Nat,
  'widthCm' : IDL.Nat,
  'bottomSide' : BottomSide,
  'heightCm' : IDL.Nat,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'emergency' : IDL.Bool,
  'clientName' : IDL.Text,
  'createdAt' : Timestamp,
  'clientStore' : IDL.Text,
  'deadline' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'parts' : IDL.Vec(Part),
});
export const TruckDimensions = IDL.Record({
  'lengthCm' : IDL.Nat,
  'widthCm' : IDL.Nat,
  'heightCm' : IDL.Nat,
});
export const TruckLoadId = IDL.Nat;
export const TruckLoadStatus = IDL.Variant({
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PartPlacement = IDL.Record({
  'posX' : IDL.Float64,
  'posY' : IDL.Float64,
  'posZ' : IDL.Float64,
  'rotW' : IDL.Float64,
  'rotX' : IDL.Float64,
  'rotY' : IDL.Float64,
  'rotZ' : IDL.Float64,
  'productId' : ProductId,
  'orderId' : OrderId,
  'partId' : PartId,
});
export const TruckLoad = IDL.Record({
  'id' : TruckLoadId,
  'status' : TruckLoadStatus,
  'loadingScheme' : IDL.Vec(PartPlacement),
  'truckDimensions' : TruckDimensions,
  'createdAt' : Timestamp,
  'orderIds' : IDL.Vec(OrderId),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addPart' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, BottomSide],
      [IDL.Opt(Part)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(OrderItem), Timestamp, IDL.Bool],
      [Order],
      [],
    ),
  'createProduct' : IDL.Func([IDL.Text], [Product], []),
  'createTruckLoad' : IDL.Func(
      [TruckDimensions, IDL.Vec(OrderId)],
      [TruckLoad],
      [],
    ),
  'deactivateProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getPrioritizedOrderIds' : IDL.Func([], [IDL.Vec(OrderId)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getTruckLoad' : IDL.Func([TruckLoadId], [IDL.Opt(TruckLoad)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], []),
  'listOrders' : IDL.Func(
      [IDL.Opt(OrderStatus), IDL.Bool],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listTruckLoads' : IDL.Func([], [IDL.Vec(TruckLoad)], ['query']),
  'optimizeTruckLoad' : IDL.Func([TruckLoadId], [IDL.Bool], []),
  'removePart' : IDL.Func([ProductId, PartId], [IDL.Bool], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveLoadingScheme' : IDL.Func(
      [TruckLoadId, IDL.Vec(PartPlacement)],
      [IDL.Bool],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'setTruckLoadStatus' : IDL.Func(
      [TruckLoadId, TruckLoadStatus],
      [IDL.Bool],
      [],
    ),
  'updateOrder' : IDL.Func(
      [OrderId, IDL.Text, IDL.Text, IDL.Vec(OrderItem), Timestamp, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updatePart' : IDL.Func(
      [
        ProductId,
        PartId,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        BottomSide,
      ],
      [IDL.Bool],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Bool, IDL.Vec(Part)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const BottomSide = IDL.Variant({
    'Top' : IDL.Null,
    'Back' : IDL.Null,
    'Left' : IDL.Null,
    'Right' : IDL.Null,
    'Front' : IDL.Null,
    'Bottom' : IDL.Null,
  });
  const PartId = IDL.Nat;
  const Part = IDL.Record({
    'id' : PartId,
    'lengthCm' : IDL.Nat,
    'widthCm' : IDL.Nat,
    'bottomSide' : BottomSide,
    'heightCm' : IDL.Nat,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'emergency' : IDL.Bool,
    'clientName' : IDL.Text,
    'createdAt' : Timestamp,
    'clientStore' : IDL.Text,
    'deadline' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'parts' : IDL.Vec(Part),
  });
  const TruckDimensions = IDL.Record({
    'lengthCm' : IDL.Nat,
    'widthCm' : IDL.Nat,
    'heightCm' : IDL.Nat,
  });
  const TruckLoadId = IDL.Nat;
  const TruckLoadStatus = IDL.Variant({
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PartPlacement = IDL.Record({
    'posX' : IDL.Float64,
    'posY' : IDL.Float64,
    'posZ' : IDL.Float64,
    'rotW' : IDL.Float64,
    'rotX' : IDL.Float64,
    'rotY' : IDL.Float64,
    'rotZ' : IDL.Float64,
    'productId' : ProductId,
    'orderId' : OrderId,
    'partId' : PartId,
  });
  const TruckLoad = IDL.Record({
    'id' : TruckLoadId,
    'status' : TruckLoadStatus,
    'loadingScheme' : IDL.Vec(PartPlacement),
    'truckDimensions' : TruckDimensions,
    'createdAt' : Timestamp,
    'orderIds' : IDL.Vec(OrderId),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addPart' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          BottomSide,
        ],
        [IDL.Opt(Part)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderItem), Timestamp, IDL.Bool],
        [Order],
        [],
      ),
    'createProduct' : IDL.Func([IDL.Text], [Product], []),
    'createTruckLoad' : IDL.Func(
        [TruckDimensions, IDL.Vec(OrderId)],
        [TruckLoad],
        [],
      ),
    'deactivateProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getPrioritizedOrderIds' : IDL.Func([], [IDL.Vec(OrderId)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getTruckLoad' : IDL.Func([TruckLoadId], [IDL.Opt(TruckLoad)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], []),
    'listOrders' : IDL.Func(
        [IDL.Opt(OrderStatus), IDL.Bool],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listTruckLoads' : IDL.Func([], [IDL.Vec(TruckLoad)], ['query']),
    'optimizeTruckLoad' : IDL.Func([TruckLoadId], [IDL.Bool], []),
    'removePart' : IDL.Func([ProductId, PartId], [IDL.Bool], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveLoadingScheme' : IDL.Func(
        [TruckLoadId, IDL.Vec(PartPlacement)],
        [IDL.Bool],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'setTruckLoadStatus' : IDL.Func(
        [TruckLoadId, TruckLoadStatus],
        [IDL.Bool],
        [],
      ),
    'updateOrder' : IDL.Func(
        [OrderId, IDL.Text, IDL.Text, IDL.Vec(OrderItem), Timestamp, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updatePart' : IDL.Func(
        [
          ProductId,
          PartId,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          BottomSide,
        ],
        [IDL.Bool],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Bool, IDL.Vec(Part)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };