/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type BottomSide = { 'Top' : null } |
  { 'Back' : null } |
  { 'Left' : null } |
  { 'Right' : null } |
  { 'Front' : null } |
  { 'Bottom' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'emergency' : boolean,
  'clientName' : string,
  'createdAt' : Timestamp,
  'clientStore' : string,
  'deadline' : Timestamp,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem { 'productId' : ProductId, 'quantity' : bigint }
export type OrderStatus = { 'Shipped' : null } |
  { 'Pending' : null };
export interface Part {
  'id' : PartId,
  'lengthCm' : bigint,
  'widthCm' : bigint,
  'bottomSide' : BottomSide,
  'heightCm' : bigint,
  'name' : string,
  'weightKg' : number,
}
export type PartId = bigint;
export interface PartPlacement {
  'posX' : number,
  'posY' : number,
  'posZ' : number,
  'rotW' : number,
  'rotX' : number,
  'rotY' : number,
  'rotZ' : number,
  'productId' : ProductId,
  'orderId' : OrderId,
  'partId' : PartId,
}
export interface Product {
  'id' : ProductId,
  'active' : boolean,
  'name' : string,
  'parts' : Array<Part>,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export interface TruckDimensions {
  'lengthCm' : bigint,
  'widthCm' : bigint,
  'heightCm' : bigint,
}
export interface TruckLoad {
  'id' : TruckLoadId,
  'status' : TruckLoadStatus,
  'loadingScheme' : Array<PartPlacement>,
  'truckDimensions' : TruckDimensions,
  'createdAt' : Timestamp,
  'orderIds' : Array<OrderId>,
}
export type TruckLoadId = bigint;
export type TruckLoadStatus = { 'Shipped' : null } |
  { 'Pending' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPart' : ActorMethod<
    [ProductId, string, bigint, bigint, bigint, number, BottomSide],
    [] | [Part]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<
    [string, string, Array<OrderItem>, Timestamp, boolean],
    Order
  >,
  'createProduct' : ActorMethod<[string], Product>,
  'createTruckLoad' : ActorMethod<[TruckDimensions, Array<OrderId>], TruckLoad>,
  'deactivateProduct' : ActorMethod<[ProductId], boolean>,
  'deleteOrder' : ActorMethod<[OrderId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getPrioritizedOrderIds' : ActorMethod<[], Array<OrderId>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getTruckLoad' : ActorMethod<[TruckLoadId], [] | [TruckLoad]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listOrders' : ActorMethod<[[] | [OrderStatus], boolean], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listTruckLoads' : ActorMethod<[], Array<TruckLoad>>,
  'optimizeTruckLoad' : ActorMethod<[TruckLoadId], boolean>,
  'removePart' : ActorMethod<[ProductId, PartId], boolean>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveLoadingScheme' : ActorMethod<
    [TruckLoadId, Array<PartPlacement>],
    boolean
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'setTruckLoadStatus' : ActorMethod<[TruckLoadId, TruckLoadStatus], boolean>,
  'updateOrder' : ActorMethod<
    [OrderId, string, string, Array<OrderItem>, Timestamp, boolean],
    boolean
  >,
  'updatePart' : ActorMethod<
    [ProductId, PartId, string, bigint, bigint, bigint, number, BottomSide],
    boolean
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, boolean, Array<Part>],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];