/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Part {
    id: PartId;
    lengthCm: bigint;
    widthCm: bigint;
    bottomSide: BottomSide;
    heightCm: bigint;
    name: string;
    weightKg: number;
}
export type PartId = bigint;
export type TruckLoadId = bigint;
export type Timestamp = bigint;
export interface TruckLoad {
    id: TruckLoadId;
    status: TruckLoadStatus;
    loadingScheme: Array<PartPlacement>;
    truckDimensions: TruckDimensions;
    createdAt: Timestamp;
    orderIds: Array<OrderId>;
}
export type OrderId = bigint;
export interface OrderItem {
    productId: ProductId;
    quantity: bigint;
}
export interface PartPlacement {
    posX: number;
    posY: number;
    posZ: number;
    rotW: number;
    rotX: number;
    rotY: number;
    rotZ: number;
    productId: ProductId;
    orderId: OrderId;
    partId: PartId;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    emergency: boolean;
    clientName: string;
    createdAt: Timestamp;
    clientStore: string;
    deadline: Timestamp;
    items: Array<OrderItem>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface TruckDimensions {
    lengthCm: bigint;
    widthCm: bigint;
    heightCm: bigint;
}
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    active: boolean;
    name: string;
    parts: Array<Part>;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum BottomSide {
    Top = "Top",
    Back = "Back",
    Left = "Left",
    Right = "Right",
    Front = "Front",
    Bottom = "Bottom"
}
export enum OrderStatus {
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addPart(productId: ProductId, name: string, lengthCm: bigint, widthCm: bigint, heightCm: bigint, weightKg: number, bottomSide: BottomSide): Promise<Part | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapAdmin(): Promise<void>;
    createOrder(clientName: string, clientStore: string, items: Array<OrderItem>, deadline: Timestamp, emergency: boolean): Promise<Order>;
    createProduct(name: string): Promise<Product>;
    createTruckLoad(truckDimensions: TruckDimensions, orderIds: Array<OrderId>): Promise<TruckLoad>;
    deactivateProduct(id: ProductId): Promise<boolean>;
    deleteOrder(id: OrderId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getOrder(id: OrderId): Promise<Order | null>;
    getPrioritizedOrderIds(): Promise<Array<OrderId>>;
    getProduct(id: ProductId): Promise<Product | null>;
    getTruckLoad(id: TruckLoadId): Promise<TruckLoad | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listOrders(statusFilter: OrderStatus | null, emergencyOnly: boolean): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    listTruckLoads(): Promise<Array<TruckLoad>>;
    optimizeTruckLoad(id: TruckLoadId): Promise<boolean>;
    removePart(productId: ProductId, partId: PartId): Promise<boolean>;
    requestApproval(): Promise<void>;
    saveLoadingScheme(id: TruckLoadId, placements: Array<PartPlacement>): Promise<boolean>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setOrderStatus(id: OrderId, status: OrderStatus): Promise<boolean>;
    setTruckLoadStatus(id: TruckLoadId, status: TruckLoadStatus): Promise<boolean>;
    updateOrder(id: OrderId, clientName: string, clientStore: string, items: Array<OrderItem>, deadline: Timestamp, emergency: boolean): Promise<boolean>;
    updatePart(productId: ProductId, partId: PartId, name: string, lengthCm: bigint, widthCm: bigint, heightCm: bigint, weightKg: number, bottomSide: BottomSide): Promise<boolean>;
    updateProduct(id: ProductId, name: string, active: boolean, parts: Array<Part>): Promise<boolean>;
}
import type { ApprovalStatus as _ApprovalStatus, BottomSide as _BottomSide, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Part as _Part, PartId as _PartId, PartPlacement as _PartPlacement, Product as _Product, ProductId as _ProductId, Timestamp as _Timestamp, TruckDimensions as _TruckDimensions, TruckLoad as _TruckLoad, TruckLoadId as _TruckLoadId, TruckLoadStatus as _TruckLoadStatus, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addPart(arg0: ProductId, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number, arg6: BottomSide): Promise<Part | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addPart(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_BottomSide_n1(this._uploadFile, this._downloadFile, arg6));
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPart(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_BottomSide_n1(this._uploadFile, this._downloadFile, arg6));
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdmin();
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: Array<OrderItem>, arg3: Timestamp, arg4: boolean): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Order_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Order_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return from_candid_Product_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return from_candid_Product_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTruckLoad(arg0: TruckDimensions, arg1: Array<OrderId>): Promise<TruckLoad> {
        if (this.processError) {
            try {
                const result = await this.actor.createTruckLoad(arg0, arg1);
                return from_candid_TruckLoad_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTruckLoad(arg0, arg1);
            return from_candid_TruckLoad_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateProduct(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: OrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrioritizedOrderIds(): Promise<Array<OrderId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrioritizedOrderIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrioritizedOrderIds();
            return result;
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTruckLoad(arg0: TruckLoadId): Promise<TruckLoad | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTruckLoad(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTruckLoad(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(arg0: OrderStatus | null, arg1: boolean): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTruckLoads(): Promise<Array<TruckLoad>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTruckLoads();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTruckLoads();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async optimizeTruckLoad(arg0: TruckLoadId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.optimizeTruckLoad(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.optimizeTruckLoad(arg0);
            return result;
        }
    }
    async removePart(arg0: ProductId, arg1: PartId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removePart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePart(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveLoadingScheme(arg0: TruckLoadId, arg1: Array<PartPlacement>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLoadingScheme(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLoadingScheme(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setTruckLoadStatus(arg0: TruckLoadId, arg1: TruckLoadStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTruckLoadStatus(arg0, to_candid_TruckLoadStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTruckLoadStatus(arg0, to_candid_TruckLoadStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrder(arg0: OrderId, arg1: string, arg2: string, arg3: Array<OrderItem>, arg4: Timestamp, arg5: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePart(arg0: ProductId, arg1: PartId, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: number, arg7: BottomSide): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePart(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_BottomSide_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePart(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_BottomSide_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: string, arg2: boolean, arg3: Array<Part>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_vec_n39(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_vec_n39(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_BottomSide_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BottomSide): BottomSide {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Part_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Part): Part {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TruckLoadStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TruckLoadStatus): TruckLoadStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TruckLoad_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TruckLoad): TruckLoad {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TruckLoad]): TruckLoad | null {
    return value.length === 0 ? null : from_candid_TruckLoad_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Part]): Part | null {
    return value.length === 0 ? null : from_candid_Part_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    emergency: boolean;
    clientName: string;
    createdAt: _Timestamp;
    clientStore: string;
    deadline: _Timestamp;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    emergency: boolean;
    clientName: string;
    createdAt: Timestamp;
    clientStore: string;
    deadline: Timestamp;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n12(_uploadFile, _downloadFile, value.status),
        emergency: value.emergency,
        clientName: value.clientName,
        createdAt: value.createdAt,
        clientStore: value.clientStore,
        deadline: value.deadline,
        items: value.items
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    active: boolean;
    name: string;
    parts: Array<_Part>;
}): {
    id: ProductId;
    active: boolean;
    name: string;
    parts: Array<Part>;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        parts: from_candid_vec_n16(_uploadFile, _downloadFile, value.parts)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TruckLoadId;
    status: _TruckLoadStatus;
    loadingScheme: Array<_PartPlacement>;
    truckDimensions: _TruckDimensions;
    createdAt: _Timestamp;
    orderIds: Array<_OrderId>;
}): {
    id: TruckLoadId;
    status: TruckLoadStatus;
    loadingScheme: Array<PartPlacement>;
    truckDimensions: TruckDimensions;
    createdAt: Timestamp;
    orderIds: Array<OrderId>;
} {
    return {
        id: value.id,
        status: from_candid_TruckLoadStatus_n19(_uploadFile, _downloadFile, value.status),
        loadingScheme: value.loadingScheme,
        truckDimensions: value.truckDimensions,
        createdAt: value.createdAt,
        orderIds: value.orderIds
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n28(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PartId;
    lengthCm: bigint;
    widthCm: bigint;
    bottomSide: _BottomSide;
    heightCm: bigint;
    name: string;
    weightKg: number;
}): {
    id: PartId;
    lengthCm: bigint;
    widthCm: bigint;
    bottomSide: BottomSide;
    heightCm: bigint;
    name: string;
    weightKg: number;
} {
    return {
        id: value.id,
        lengthCm: value.lengthCm,
        widthCm: value.widthCm,
        bottomSide: from_candid_BottomSide_n6(_uploadFile, _downloadFile, value.bottomSide),
        heightCm: value.heightCm,
        name: value.name,
        weightKg: value.weightKg
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Top: null;
} | {
    Back: null;
} | {
    Left: null;
} | {
    Right: null;
} | {
    Front: null;
} | {
    Bottom: null;
}): BottomSide {
    return "Top" in value ? BottomSide.Top : "Back" in value ? BottomSide.Back : "Left" in value ? BottomSide.Left : "Right" in value ? BottomSide.Right : "Front" in value ? BottomSide.Front : "Bottom" in value ? BottomSide.Bottom : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Part>): Array<Part> {
    return value.map((x)=>from_candid_Part_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TruckLoad>): Array<TruckLoad> {
    return value.map((x)=>from_candid_TruckLoad_n17(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_BottomSide_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BottomSide): _BottomSide {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Part_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Part): _Part {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TruckLoadStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TruckLoadStatus): _TruckLoadStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus | null): [] | [_OrderStatus] {
    return value === null ? candid_none() : candid_some(to_candid_OrderStatus_n31(_uploadFile, _downloadFile, value));
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PartId;
    lengthCm: bigint;
    widthCm: bigint;
    bottomSide: BottomSide;
    heightCm: bigint;
    name: string;
    weightKg: number;
}): {
    id: _PartId;
    lengthCm: bigint;
    widthCm: bigint;
    bottomSide: _BottomSide;
    heightCm: bigint;
    name: string;
    weightKg: number;
} {
    return {
        id: value.id,
        lengthCm: value.lengthCm,
        widthCm: value.widthCm,
        bottomSide: to_candid_BottomSide_n1(_uploadFile, _downloadFile, value.bottomSide),
        heightCm: value.heightCm,
        name: value.name,
        weightKg: value.weightKg
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BottomSide): {
    Top: null;
} | {
    Back: null;
} | {
    Left: null;
} | {
    Right: null;
} | {
    Front: null;
} | {
    Bottom: null;
} {
    return value == BottomSide.Top ? {
        Top: null
    } : value == BottomSide.Back ? {
        Back: null
    } : value == BottomSide.Left ? {
        Left: null
    } : value == BottomSide.Right ? {
        Right: null
    } : value == BottomSide.Front ? {
        Front: null
    } : value == BottomSide.Bottom ? {
        Bottom: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Shipped: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Part>): Array<_Part> {
    return value.map((x)=>to_candid_Part_n40(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
